$axure.loadCurrentPage({
  "url":"厂商注册界面.html",
  "generationDate":new Date(1438248553218.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"usertype"],
  "page":{
    "packageId":"8926b90da8b64501a978629b85d18fd6",
    "type":"Axure:Page",
    "name":"厂商注册界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"隐藏 提示窗/(形状),<br>提示窗/(形状),<br>提示窗/(形状)",
                "objectsToFades":[{
                    "objectPath":["f6ce47c3ab6e4b28ab36f644784f32b0",
"39d54c5b04ef45d4ab43099f4e071df2"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["f6ce47c3ab6e4b28ab36f644784f32b0",
"861932a815a14dd4bd7bd609d1dc821e"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["f6ce47c3ab6e4b28ab36f644784f32b0",
"0a648b4817244d338323d98cbea4a89b"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"4789893064004b7c90d336e78ecfce7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":22},
            "size":{
              "width":1024,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a2f15f462c245f692d5fc7c183db221",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":22},
                "size":{
                  "width":1024,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"81fd192cfaa34d568aff0596883bba01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":120},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a8f7f8cacd340b3b83d691b327bce74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":120},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"13e3354f3a484c298cdaf3035d937ba1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":668},
            "size":{
              "width":1000,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u4_line.png"}},
{
          "id":"635b930b853f4294b32516c065411017",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":180,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47f886fd83bd4f8092bee3a672a6129e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":180,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}},
{
          "id":"aa0dbe36027b4e0992697b3fc5161c7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":160},
            "size":{
              "width":620,
              "height":451},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cc5775e6f6540e8983801eec8c6ba38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":202,
                  "y":160},
                "size":{
                  "width":620,
                  "height":451},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/厂商注册界面/u7.png"}},
{
          "id":"9517f70ba31b41c5b5ae91b2b5ffba4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":920,
              "y":49},
            "size":{
              "width":64,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac96d447eaaf447daa1a20bde75b3b2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":920,
                  "y":49},
                "size":{
                  "width":64,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41298fd8ee0643709c748226bde034f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":318,
              "y":532},
            "size":{
              "width":155,
              "height":58},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b59d8e15d4a413695be357c36adbbb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":318,
                  "y":532},
                "size":{
                  "width":155,
                  "height":58},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 提示窗/(形状),<br>提示窗/(形状),<br>提示窗/(形状)",
                      "objectsToFades":[{
                          "objectPath":["f6ce47c3ab6e4b28ab36f644784f32b0",
"39d54c5b04ef45d4ab43099f4e071df2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f6ce47c3ab6e4b28ab36f644784f32b0",
"861932a815a14dd4bd7bd609d1dc821e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f6ce47c3ab6e4b28ab36f644784f32b0",
"0a648b4817244d338323d98cbea4a89b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/厂商注册界面/u11.png"}},
{
          "id":"5e9b0045fd0a43d3bd9d44c34033b92a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":551,
              "y":532},
            "size":{
              "width":155,
              "height":58},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a83e0d68c72641448b5cd48be12ff2ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":551,
                  "y":532},
                "size":{
                  "width":155,
                  "height":58},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/厂商注册界面/u11.png"}},
{
          "id":"656d1d8623bb4cb7affa5e2770c5f623",
          "label":"密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":404,
              "y":314},
            "size":{
              "width":310,
              "height":36}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入至少8位字母或数字"},
{
          "id":"6216576467a2460794842483baa7e3b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":306,
              "y":274},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0020486a91004d51863bb6626e85dc8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":306,
                  "y":274},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31afbaa4740c4e53bace1629bffdf852",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":306,
              "y":322},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55908abbc64a4070960eb02fafd0e71e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":306,
                  "y":322},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e846514960e4f26b97789fd23e1bb05",
          "label":"用户名",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":404,
              "y":214},
            "size":{
              "width":310,
              "height":40}},
          "adaptiveStyles":{
},
          "placeholderText":"手机号/用户名"},
{
          "id":"5e91ded986844f1f820178e20192768e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":306,
              "y":225},
            "size":{
              "width":69,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01e5b05829934cd0b2f0841563b94066",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":306,
                  "y":225},
                "size":{
                  "width":69,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96fab18c8ac440ee831517d68e3cca68",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'华文行楷 Regular', '华文行楷'",
            "fontSize":"48px",
            "fontWeight":"400",
            "location":{
              "x":306,
              "y":34},
            "size":{
              "width":385,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2b2de73f55f4e0ba31c903269a1f8ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文行楷 Regular', '华文行楷'",
                "fontSize":"48px",
                "fontWeight":"400",
                "location":{
                  "x":306,
                  "y":34},
                "size":{
                  "width":385,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cde27d3b617d45f6968dc81eb1c4fc43",
          "label":"年龄",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":404,
              "y":264},
            "size":{
              "width":310,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"f6ce47c3ab6e4b28ab36f644784f32b0",
          "label":"提示窗",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":323},
            "size":{
              "width":287,
              "height":166}},
          "adaptiveStyles":{
},
          "masterId":"c1023ce194f8408e9856cfe74a318fef"},
{
          "id":"bec104e3de7248acb8a4256bbe305443",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":120},
            "size":{
              "width":151,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40f37d05aacf4bf2993c8abe2006f4f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":151,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "c1023ce194f8408e9856cfe74a318fef":{
      "packageId":"c1023ce194f8408e9856cfe74a318fef",
      "type":"Axure:Master",
      "name":"提示窗",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"39d54c5b04ef45d4ab43099f4e071df2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":287,
                "height":166}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81694b28c5cf44c99fb27df555fe46fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":287,
                    "height":166}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/厂商注册界面/u27.png"}},
{
            "id":"861932a815a14dd4bd7bd609d1dc821e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "location":{
                "x":66,
                "y":104},
              "size":{
                "width":155,
                "height":37},
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"db528f5c37ee45109eb6e93c789cab23",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "location":{
                    "x":66,
                    "y":104},
                  "size":{
                    "width":155,
                    "height":37},
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主界面",
                        "target":{
                          "targetType":"page",
                          "url":"主界面.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/厂商注册界面/u29.png"}},
{
            "id":"0a648b4817244d338323d98cbea4a89b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":85.5,
                "y":36},
              "size":{
                "width":126,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a8be36ddfd6a4da6926ce1b634d0819c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":85.5,
                    "y":36},
                  "size":{
                    "width":126,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "4789893064004b7c90d336e78ecfce7f":{
      "scriptId":"u0"},
    "9a2f15f462c245f692d5fc7c183db221":{
      "scriptId":"u1"},
    "81fd192cfaa34d568aff0596883bba01":{
      "scriptId":"u2"},
    "7a8f7f8cacd340b3b83d691b327bce74":{
      "scriptId":"u3"},
    "13e3354f3a484c298cdaf3035d937ba1":{
      "scriptId":"u4"},
    "635b930b853f4294b32516c065411017":{
      "scriptId":"u5"},
    "47f886fd83bd4f8092bee3a672a6129e":{
      "scriptId":"u6"},
    "aa0dbe36027b4e0992697b3fc5161c7e":{
      "scriptId":"u7"},
    "3cc5775e6f6540e8983801eec8c6ba38":{
      "scriptId":"u8"},
    "9517f70ba31b41c5b5ae91b2b5ffba4b":{
      "scriptId":"u9"},
    "ac96d447eaaf447daa1a20bde75b3b2b":{
      "scriptId":"u10"},
    "41298fd8ee0643709c748226bde034f2":{
      "scriptId":"u11"},
    "7b59d8e15d4a413695be357c36adbbb5":{
      "scriptId":"u12"},
    "5e9b0045fd0a43d3bd9d44c34033b92a":{
      "scriptId":"u13"},
    "a83e0d68c72641448b5cd48be12ff2ec":{
      "scriptId":"u14"},
    "656d1d8623bb4cb7affa5e2770c5f623":{
      "scriptId":"u15"},
    "6216576467a2460794842483baa7e3b2":{
      "scriptId":"u16"},
    "0020486a91004d51863bb6626e85dc8c":{
      "scriptId":"u17"},
    "31afbaa4740c4e53bace1629bffdf852":{
      "scriptId":"u18"},
    "55908abbc64a4070960eb02fafd0e71e":{
      "scriptId":"u19"},
    "7e846514960e4f26b97789fd23e1bb05":{
      "scriptId":"u20"},
    "5e91ded986844f1f820178e20192768e":{
      "scriptId":"u21"},
    "01e5b05829934cd0b2f0841563b94066":{
      "scriptId":"u22"},
    "96fab18c8ac440ee831517d68e3cca68":{
      "scriptId":"u23"},
    "b2b2de73f55f4e0ba31c903269a1f8ce":{
      "scriptId":"u24"},
    "cde27d3b617d45f6968dc81eb1c4fc43":{
      "scriptId":"u25"},
    "f6ce47c3ab6e4b28ab36f644784f32b0":{
      "scriptId":"u26",
      "39d54c5b04ef45d4ab43099f4e071df2":{
        "scriptId":"u27"},
      "81694b28c5cf44c99fb27df555fe46fb":{
        "scriptId":"u28"},
      "861932a815a14dd4bd7bd609d1dc821e":{
        "scriptId":"u29"},
      "db528f5c37ee45109eb6e93c789cab23":{
        "scriptId":"u30"},
      "0a648b4817244d338323d98cbea4a89b":{
        "scriptId":"u31"},
      "a8be36ddfd6a4da6926ce1b634d0819c":{
        "scriptId":"u32"}},
    "bec104e3de7248acb8a4256bbe305443":{
      "scriptId":"u33"},
    "40f37d05aacf4bf2993c8abe2006f4f0":{
      "scriptId":"u34"}}});