$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1438248552984.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"usertype"],
  "page":{
    "packageId":"b4d09ba1785d4354988f603acc71a400",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[]}]}},
    "diagram":{
      "objects":[{
          "id":"eba3d3b8c4474cf79b7ae549c20f9fe4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":22},
            "size":{
              "width":1024,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a30976ab39484a3b9b56daa58f7d08ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":22},
                "size":{
                  "width":1024,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"975b0a898eb147f4bdb093d24b3f9e9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":120},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6def13ecd044ba5a224863c49ebafe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":120},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"4c72e373caeb4926a2c161b69683a472",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":668},
            "size":{
              "width":1000,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u4_line.png"}},
{
          "id":"1c4a092af0fc4bf8ac11ca61da95d61c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":180,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5537a64071d245df960032074880736c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":180,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}},
{
          "id":"05389ee1a14f42b9807b9ebe0bcf9335",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":240},
            "size":{
              "width":400,
              "height":310},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eca21c6ac79e4105a543cae0e4e7b7e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":240},
                "size":{
                  "width":400,
                  "height":310},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u7.png"}},
{
          "id":"403ca5936aa04211885bba3a3594fb78",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":920,
              "y":49},
            "size":{
              "width":64,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4725becaff5f414ab4315e2e36a4b39c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":920,
                  "y":49},
                "size":{
                  "width":64,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39018c70043640959e6aa360ac22231d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":678,
              "y":458},
            "size":{
              "width":100,
              "height":40},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d11049d4261433eaa7d330725bb2163",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":678,
                  "y":458},
                "size":{
                  "width":100,
                  "height":40},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If 选中项值 角色选择 = &quot;用户&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["2677037e73544b8fa9347ca33ced5e84"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"用户",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户注册界面",
                      "target":{
                        "targetType":"page",
                        "url":"用户注册界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 2<br> (Else If 选中项值 角色选择 = &quot;医生&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["2677037e73544b8fa9347ca33ced5e84"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"医生",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 医生注册界面",
                      "target":{
                        "targetType":"page",
                        "url":"医生注册界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 3<br> (Else If 选中项值 角色选择 = &quot;设备厂商&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["2677037e73544b8fa9347ca33ced5e84"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"设备厂商",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 厂商注册界面",
                      "target":{
                        "targetType":"page",
                        "url":"厂商注册界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 4<br> (Else If 选中项值 角色选择 = &quot;保险公司&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["2677037e73544b8fa9347ca33ced5e84"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"保险公司",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 保险公司注册界面",
                      "target":{
                        "targetType":"page",
                        "url":"保险公司注册界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u11.png"}},
{
          "id":"96ab9b4133144d4b91f2d1ca657667d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":828,
              "y":458},
            "size":{
              "width":100,
              "height":40},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab6b5938625440c3bf61e3c6114ab2ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":828,
                  "y":458},
                "size":{
                  "width":100,
                  "height":40},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u11.png"}},
{
          "id":"7aa9b71a7f04443cb123d24f7a57b8ce",
          "label":"密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":732,
              "y":408},
            "size":{
              "width":200,
              "height":35}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入至少8位字母或数字"},
{
          "id":"51d9306dfa894cfbb72ce1dcc46b984e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":668,
              "y":360},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10d745311281436f9080300dc532a0d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":668,
                  "y":360},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"814a3c957a624b9caaf0ba5e13ffbb37",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":668,
              "y":418},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c94541a7b2945f5a0abf5f093411e8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":668,
                  "y":418},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45ce4c769ad340d6ae24467f0e2cf9fd",
          "label":"用户名",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":732,
              "y":292},
            "size":{
              "width":200,
              "height":35}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入手机号/用户名"},
{
          "id":"7dc2fd09dd2545eaa3fd7ddfacea6fb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":668,
              "y":300},
            "size":{
              "width":52,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"495c1a6373904c678a3625410b6b1605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":668,
                  "y":300},
                "size":{
                  "width":52,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a37acfcc9f764517a8697d85c8eb27e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'华文行楷 Regular', '华文行楷'",
            "fontSize":"48px",
            "fontWeight":"400",
            "location":{
              "x":306,
              "y":33.5},
            "size":{
              "width":385,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65ce3203591246f280ef26910131a3af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文行楷 Regular', '华文行楷'",
                "fontSize":"48px",
                "fontWeight":"400",
                "location":{
                  "x":306,
                  "y":33.5},
                "size":{
                  "width":385,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2677037e73544b8fa9347ca33ced5e84",
          "label":"角色选择",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":732,
              "y":352},
            "size":{
              "width":200,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"894a6ccdc9614280b3cab174d50e483e",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":240},
            "size":{
              "width":526,
              "height":310}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"webUrl",
            "urlLiteral":{
              "exprType":"stringLiteral",
              "value":"http://www.dehaier.com.cn/Home/flash/flash3.swf",
              "stos":[]},
            "includeVariables":false}}]}},
  "masters":{
},
  "objectPaths":{
    "eba3d3b8c4474cf79b7ae549c20f9fe4":{
      "scriptId":"u0"},
    "a30976ab39484a3b9b56daa58f7d08ec":{
      "scriptId":"u1"},
    "975b0a898eb147f4bdb093d24b3f9e9c":{
      "scriptId":"u2"},
    "f6def13ecd044ba5a224863c49ebafe7":{
      "scriptId":"u3"},
    "4c72e373caeb4926a2c161b69683a472":{
      "scriptId":"u4"},
    "1c4a092af0fc4bf8ac11ca61da95d61c":{
      "scriptId":"u5"},
    "5537a64071d245df960032074880736c":{
      "scriptId":"u6"},
    "05389ee1a14f42b9807b9ebe0bcf9335":{
      "scriptId":"u7"},
    "eca21c6ac79e4105a543cae0e4e7b7e5":{
      "scriptId":"u8"},
    "403ca5936aa04211885bba3a3594fb78":{
      "scriptId":"u9"},
    "4725becaff5f414ab4315e2e36a4b39c":{
      "scriptId":"u10"},
    "39018c70043640959e6aa360ac22231d":{
      "scriptId":"u11"},
    "4d11049d4261433eaa7d330725bb2163":{
      "scriptId":"u12"},
    "96ab9b4133144d4b91f2d1ca657667d8":{
      "scriptId":"u13"},
    "ab6b5938625440c3bf61e3c6114ab2ca":{
      "scriptId":"u14"},
    "7aa9b71a7f04443cb123d24f7a57b8ce":{
      "scriptId":"u15"},
    "51d9306dfa894cfbb72ce1dcc46b984e":{
      "scriptId":"u16"},
    "10d745311281436f9080300dc532a0d3":{
      "scriptId":"u17"},
    "814a3c957a624b9caaf0ba5e13ffbb37":{
      "scriptId":"u18"},
    "2c94541a7b2945f5a0abf5f093411e8e":{
      "scriptId":"u19"},
    "45ce4c769ad340d6ae24467f0e2cf9fd":{
      "scriptId":"u20"},
    "7dc2fd09dd2545eaa3fd7ddfacea6fb6":{
      "scriptId":"u21"},
    "495c1a6373904c678a3625410b6b1605":{
      "scriptId":"u22"},
    "a37acfcc9f764517a8697d85c8eb27e3":{
      "scriptId":"u23"},
    "65ce3203591246f280ef26910131a3af":{
      "scriptId":"u24"},
    "2677037e73544b8fa9347ca33ced5e84":{
      "scriptId":"u25"},
    "894a6ccdc9614280b3cab174d50e483e":{
      "scriptId":"u26"}}});