$axure.loadCurrentPage({
  "url":"保险公司注册界面.html",
  "generationDate":new Date(1438248553406.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"usertype"],
  "page":{
    "packageId":"5b7fde32479d4d7285193c9ea5341add",
    "type":"Axure:Page",
    "name":"保险公司注册界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"隐藏 提示窗/(形状),<br>提示窗/(形状),<br>提示窗/(形状)",
                "objectsToFades":[{
                    "objectPath":["d6176e2c8cf0425cb75bd4faa40bb866",
"39d54c5b04ef45d4ab43099f4e071df2"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["d6176e2c8cf0425cb75bd4faa40bb866",
"861932a815a14dd4bd7bd609d1dc821e"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["d6176e2c8cf0425cb75bd4faa40bb866",
"0a648b4817244d338323d98cbea4a89b"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"f7c6fc35bebd4ec8a7cf1806cea9e476",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":22},
            "size":{
              "width":1024,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20c0cee6a9644226a9574a9959e2f9af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":22},
                "size":{
                  "width":1024,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"875b61c637d34cfc8000528a9036a92d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":120},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30a7725e5b3b4b1180dca15df03dcd32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":120},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"ab1e3e11b2834cbd89ae9f1e493cf6cb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":668},
            "size":{
              "width":1000,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u4_line.png"}},
{
          "id":"4a4fc91bd1bb4ee99f83a88ab7564e31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":180,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab040d9055004c7fbc6a6b60319aa113",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":180,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}},
{
          "id":"58c6a7eb535441389a6dcfdc3948484a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":160},
            "size":{
              "width":620,
              "height":451},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61469e79871a4fce869bcfa5bf49daba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":202,
                  "y":160},
                "size":{
                  "width":620,
                  "height":451},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/厂商注册界面/u7.png"}},
{
          "id":"5a4e753bfc674e099768a3dd6aea36b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":920,
              "y":49},
            "size":{
              "width":64,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"492e606699e54c26b59aff0eff5c1569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":920,
                  "y":49},
                "size":{
                  "width":64,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2d42c5bb26545ce8d8db99606b1cfda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":318,
              "y":532},
            "size":{
              "width":155,
              "height":58},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"975782eef2724d19b6b9329b534ce4ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":318,
                  "y":532},
                "size":{
                  "width":155,
                  "height":58},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 提示窗/(形状),<br>提示窗/(形状),<br>提示窗/(形状)",
                      "objectsToFades":[{
                          "objectPath":["d6176e2c8cf0425cb75bd4faa40bb866",
"39d54c5b04ef45d4ab43099f4e071df2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d6176e2c8cf0425cb75bd4faa40bb866",
"861932a815a14dd4bd7bd609d1dc821e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d6176e2c8cf0425cb75bd4faa40bb866",
"0a648b4817244d338323d98cbea4a89b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/厂商注册界面/u11.png"}},
{
          "id":"8607eaf27ca34d27bc40c470a85df617",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":551,
              "y":532},
            "size":{
              "width":155,
              "height":58},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e729eb06393b4bf2a3c4db7a48e9c934",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":551,
                  "y":532},
                "size":{
                  "width":155,
                  "height":58},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/厂商注册界面/u11.png"}},
{
          "id":"0bfeb11c708049a287b867741172502b",
          "label":"密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":404,
              "y":314},
            "size":{
              "width":310,
              "height":36}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入至少8位字母或数字"},
{
          "id":"67fd9bc68cbf4cc099c26dd227e1cc9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":306,
              "y":274},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79c4527b909440c49ea61d7a3e77b0ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":306,
                  "y":274},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc95415898a24fa69d70df96957cb15a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":306,
              "y":322},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c14d6f8decc4bc89f3f8651c4b1629e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":306,
                  "y":322},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bfb901e2c2c4068a6461da56512bff4",
          "label":"用户名",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":404,
              "y":214},
            "size":{
              "width":310,
              "height":40}},
          "adaptiveStyles":{
},
          "placeholderText":"手机号/用户名"},
{
          "id":"85e8e2969bed438ea3eb78c4c67c58df",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":306,
              "y":225},
            "size":{
              "width":69,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d0aab03ac3249db81776af7320eed61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":306,
                  "y":225},
                "size":{
                  "width":69,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e90cb8b3bac74133810f74e459a4d247",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'华文行楷 Regular', '华文行楷'",
            "fontSize":"48px",
            "fontWeight":"400",
            "location":{
              "x":306,
              "y":34},
            "size":{
              "width":385,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"258932863c084b6fa41125b76972977d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文行楷 Regular', '华文行楷'",
                "fontSize":"48px",
                "fontWeight":"400",
                "location":{
                  "x":306,
                  "y":34},
                "size":{
                  "width":385,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67fe65e0efe645a9974fc437bf3fc9fd",
          "label":"年龄",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":404,
              "y":264},
            "size":{
              "width":310,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"d6176e2c8cf0425cb75bd4faa40bb866",
          "label":"提示窗",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":323},
            "size":{
              "width":287,
              "height":166}},
          "adaptiveStyles":{
},
          "masterId":"c1023ce194f8408e9856cfe74a318fef"},
{
          "id":"88d7830b291f4ba48d58e6a618650cec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":120},
            "size":{
              "width":151,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de71a8a1a965441dbbe59e5cd67d5df4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":151,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "c1023ce194f8408e9856cfe74a318fef":{
      "packageId":"c1023ce194f8408e9856cfe74a318fef",
      "type":"Axure:Master",
      "name":"提示窗",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"39d54c5b04ef45d4ab43099f4e071df2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":287,
                "height":166}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81694b28c5cf44c99fb27df555fe46fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":287,
                    "height":166}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/厂商注册界面/u27.png"}},
{
            "id":"861932a815a14dd4bd7bd609d1dc821e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "location":{
                "x":66,
                "y":104},
              "size":{
                "width":155,
                "height":37},
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"db528f5c37ee45109eb6e93c789cab23",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "location":{
                    "x":66,
                    "y":104},
                  "size":{
                    "width":155,
                    "height":37},
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主界面",
                        "target":{
                          "targetType":"page",
                          "url":"主界面.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/厂商注册界面/u29.png"}},
{
            "id":"0a648b4817244d338323d98cbea4a89b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":85.5,
                "y":36},
              "size":{
                "width":126,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a8be36ddfd6a4da6926ce1b634d0819c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":85.5,
                    "y":36},
                  "size":{
                    "width":126,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "f7c6fc35bebd4ec8a7cf1806cea9e476":{
      "scriptId":"u0"},
    "20c0cee6a9644226a9574a9959e2f9af":{
      "scriptId":"u1"},
    "875b61c637d34cfc8000528a9036a92d":{
      "scriptId":"u2"},
    "30a7725e5b3b4b1180dca15df03dcd32":{
      "scriptId":"u3"},
    "ab1e3e11b2834cbd89ae9f1e493cf6cb":{
      "scriptId":"u4"},
    "4a4fc91bd1bb4ee99f83a88ab7564e31":{
      "scriptId":"u5"},
    "ab040d9055004c7fbc6a6b60319aa113":{
      "scriptId":"u6"},
    "58c6a7eb535441389a6dcfdc3948484a":{
      "scriptId":"u7"},
    "61469e79871a4fce869bcfa5bf49daba":{
      "scriptId":"u8"},
    "5a4e753bfc674e099768a3dd6aea36b4":{
      "scriptId":"u9"},
    "492e606699e54c26b59aff0eff5c1569":{
      "scriptId":"u10"},
    "f2d42c5bb26545ce8d8db99606b1cfda":{
      "scriptId":"u11"},
    "975782eef2724d19b6b9329b534ce4ef":{
      "scriptId":"u12"},
    "8607eaf27ca34d27bc40c470a85df617":{
      "scriptId":"u13"},
    "e729eb06393b4bf2a3c4db7a48e9c934":{
      "scriptId":"u14"},
    "0bfeb11c708049a287b867741172502b":{
      "scriptId":"u15"},
    "67fd9bc68cbf4cc099c26dd227e1cc9a":{
      "scriptId":"u16"},
    "79c4527b909440c49ea61d7a3e77b0ba":{
      "scriptId":"u17"},
    "fc95415898a24fa69d70df96957cb15a":{
      "scriptId":"u18"},
    "6c14d6f8decc4bc89f3f8651c4b1629e":{
      "scriptId":"u19"},
    "4bfb901e2c2c4068a6461da56512bff4":{
      "scriptId":"u20"},
    "85e8e2969bed438ea3eb78c4c67c58df":{
      "scriptId":"u21"},
    "5d0aab03ac3249db81776af7320eed61":{
      "scriptId":"u22"},
    "e90cb8b3bac74133810f74e459a4d247":{
      "scriptId":"u23"},
    "258932863c084b6fa41125b76972977d":{
      "scriptId":"u24"},
    "67fe65e0efe645a9974fc437bf3fc9fd":{
      "scriptId":"u25"},
    "d6176e2c8cf0425cb75bd4faa40bb866":{
      "scriptId":"u26",
      "39d54c5b04ef45d4ab43099f4e071df2":{
        "scriptId":"u27"},
      "81694b28c5cf44c99fb27df555fe46fb":{
        "scriptId":"u28"},
      "861932a815a14dd4bd7bd609d1dc821e":{
        "scriptId":"u29"},
      "db528f5c37ee45109eb6e93c789cab23":{
        "scriptId":"u30"},
      "0a648b4817244d338323d98cbea4a89b":{
        "scriptId":"u31"},
      "a8be36ddfd6a4da6926ce1b634d0819c":{
        "scriptId":"u32"}},
    "88d7830b291f4ba48d58e6a618650cec":{
      "scriptId":"u33"},
    "de71a8a1a965441dbbe59e5cd67d5df4":{
      "scriptId":"u34"}}});