$axure.loadCurrentPage({
  "url":"主界面.html",
  "generationDate":new Date(1438248554046.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"usertype"],
  "page":{
    "packageId":"332e354a51c647beace0be287b440166",
    "type":"Axure:Page",
    "name":"主界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"65d20c3463904dd2a12bd1dcc46f333b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":22},
            "size":{
              "width":1024,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6403007c7da44e1a9a2cf5111035dceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":22},
                "size":{
                  "width":1024,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"88669b0a9e164398becbd9f50b0394f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":120},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eede150716ba445fab90a2f90269c315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":120},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"63e717cf419c455986d244ded137f871",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":668},
            "size":{
              "width":1000,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u4_line.png"}},
{
          "id":"5e83107dafe44bd7abb098d19b2a6d6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":180,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdb0744b9d234fc2aec425c4c5a5eadf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":180,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}},
{
          "id":"6bb1056fd39845bf90f8a5b9a8116464",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":240},
            "size":{
              "width":400,
              "height":310},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dca1230f2a11465c88ae13f618893497",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":240},
                "size":{
                  "width":400,
                  "height":310},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u7.png"}},
{
          "id":"a9f920b7343d43e0984b16ef707caaf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":920,
              "y":49},
            "size":{
              "width":64,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d4e6dae741f4252946debd2d09f5a6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":920,
                  "y":49},
                "size":{
                  "width":64,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5a7cc0b5d7c4fa59e252fed784290e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":678,
              "y":458},
            "size":{
              "width":100,
              "height":40},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a41f04705b1488892f2fc483d5c0cd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":678,
                  "y":458},
                "size":{
                  "width":100,
                  "height":40},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If 选中项值 角色选择 = &quot;用户&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["50c4d6b8340e462894c39c65b4aa1119"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"用户",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户注册界面",
                      "target":{
                        "targetType":"page",
                        "url":"用户注册界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 2<br> (Else If 选中项值 角色选择 = &quot;医生&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["50c4d6b8340e462894c39c65b4aa1119"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"医生",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 医生注册界面",
                      "target":{
                        "targetType":"page",
                        "url":"医生注册界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 3<br> (Else If 选中项值 角色选择 = &quot;设备厂商&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["50c4d6b8340e462894c39c65b4aa1119"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"设备厂商",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 厂商注册界面",
                      "target":{
                        "targetType":"page",
                        "url":"厂商注册界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 4<br> (Else If 选中项值 角色选择 = &quot;保险公司&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["50c4d6b8340e462894c39c65b4aa1119"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"保险公司",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 保险公司注册界面",
                      "target":{
                        "targetType":"page",
                        "url":"保险公司注册界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u11.png"}},
{
          "id":"ca9b7c48bcc44f38a267c63c94d83540",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":828,
              "y":458},
            "size":{
              "width":100,
              "height":40},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f3650877b694c6d94dc9d87b37674c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":828,
                  "y":458},
                "size":{
                  "width":100,
                  "height":40},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u11.png"}},
{
          "id":"31d00110baa44553aed76ea5b81d65ce",
          "label":"密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":732,
              "y":408},
            "size":{
              "width":200,
              "height":35}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入至少8位字母或数字"},
{
          "id":"69924475428442ea8ec80d3a91ebfaef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":668,
              "y":360},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa394de83de74586b4b7b5e4c201e247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":668,
                  "y":360},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0077403f4cd94c5b94a65be968f58760",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":668,
              "y":418},
            "size":{
              "width":35,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01f74cf0374542de8b50ca7857a3136d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":668,
                  "y":418},
                "size":{
                  "width":35,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8c1511fce524e939ee478ef6eed0eab",
          "label":"用户名",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":732,
              "y":292},
            "size":{
              "width":200,
              "height":35}},
          "adaptiveStyles":{
},
          "placeholderText":"手机号/用户名"},
{
          "id":"51926d436dbb48c1980684abe7b457e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":668,
              "y":300},
            "size":{
              "width":52,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b68e94a7c0d04c55a3f6d2eafe6f1465",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":668,
                  "y":300},
                "size":{
                  "width":52,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8989d7e5df147e4b587422730417096",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'华文行楷 Regular', '华文行楷'",
            "fontSize":"48px",
            "fontWeight":"400",
            "location":{
              "x":306,
              "y":34},
            "size":{
              "width":385,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1ef76f481884512a9941b7adf195bf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文行楷 Regular', '华文行楷'",
                "fontSize":"48px",
                "fontWeight":"400",
                "location":{
                  "x":306,
                  "y":34},
                "size":{
                  "width":385,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50c4d6b8340e462894c39c65b4aa1119",
          "label":"角色选择",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":732,
              "y":352},
            "size":{
              "width":200,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"80dd5b63a1f0497dab02288ef761e4b9",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":240},
            "size":{
              "width":526,
              "height":310}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"webUrl",
            "urlLiteral":{
              "exprType":"stringLiteral",
              "value":"http://www.dehaier.com.cn/Home/flash/flash3.swf",
              "stos":[]},
            "includeVariables":false}},
{
          "id":"ca11ab7ec2af4c1eb39d31e1de714ea1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":120},
            "size":{
              "width":76,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e552efbc97384906926bf10ba2256abb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":76,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "65d20c3463904dd2a12bd1dcc46f333b":{
      "scriptId":"u0"},
    "6403007c7da44e1a9a2cf5111035dceb":{
      "scriptId":"u1"},
    "88669b0a9e164398becbd9f50b0394f9":{
      "scriptId":"u2"},
    "eede150716ba445fab90a2f90269c315":{
      "scriptId":"u3"},
    "63e717cf419c455986d244ded137f871":{
      "scriptId":"u4"},
    "5e83107dafe44bd7abb098d19b2a6d6e":{
      "scriptId":"u5"},
    "fdb0744b9d234fc2aec425c4c5a5eadf":{
      "scriptId":"u6"},
    "6bb1056fd39845bf90f8a5b9a8116464":{
      "scriptId":"u7"},
    "dca1230f2a11465c88ae13f618893497":{
      "scriptId":"u8"},
    "a9f920b7343d43e0984b16ef707caaf0":{
      "scriptId":"u9"},
    "6d4e6dae741f4252946debd2d09f5a6a":{
      "scriptId":"u10"},
    "e5a7cc0b5d7c4fa59e252fed784290e3":{
      "scriptId":"u11"},
    "0a41f04705b1488892f2fc483d5c0cd4":{
      "scriptId":"u12"},
    "ca9b7c48bcc44f38a267c63c94d83540":{
      "scriptId":"u13"},
    "6f3650877b694c6d94dc9d87b37674c8":{
      "scriptId":"u14"},
    "31d00110baa44553aed76ea5b81d65ce":{
      "scriptId":"u15"},
    "69924475428442ea8ec80d3a91ebfaef":{
      "scriptId":"u16"},
    "aa394de83de74586b4b7b5e4c201e247":{
      "scriptId":"u17"},
    "0077403f4cd94c5b94a65be968f58760":{
      "scriptId":"u18"},
    "01f74cf0374542de8b50ca7857a3136d":{
      "scriptId":"u19"},
    "e8c1511fce524e939ee478ef6eed0eab":{
      "scriptId":"u20"},
    "51926d436dbb48c1980684abe7b457e7":{
      "scriptId":"u21"},
    "b68e94a7c0d04c55a3f6d2eafe6f1465":{
      "scriptId":"u22"},
    "e8989d7e5df147e4b587422730417096":{
      "scriptId":"u23"},
    "e1ef76f481884512a9941b7adf195bf2":{
      "scriptId":"u24"},
    "50c4d6b8340e462894c39c65b4aa1119":{
      "scriptId":"u25"},
    "80dd5b63a1f0497dab02288ef761e4b9":{
      "scriptId":"u26"},
    "ca11ab7ec2af4c1eb39d31e1de714ea1":{
      "scriptId":"u27"},
    "e552efbc97384906926bf10ba2256abb":{
      "scriptId":"u28"}}});